apiVersion: v1
kind: Namespace
metadata:
  name: app1
---
apiVersion: v1
kind: Secret
metadata:
  name: front-secrets
  namespace: app1
type: Opaque
stringData:
  BACK1_URL: ''
---
apiVersion: v1
kind: Service
metadata:
  name: front-svc
  namespace: app1
spec:
  selector:
    app: hello-tilt-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: front-ingress
  namespace: app1
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
        - path: /front(/|$)(.*)
          backend:
            service:
              name: front-svc
              port:
                number: 80
          pathType: Prefix
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-tilt-front
  namespace: app1
spec:
  selector:
    matchLabels:
      app: hello-tilt-front
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-tilt-front
        app-type: nginx-frontend
      annotations:
        co.elastic.logs/module: "nginx"
        co.elastic.logs/fileset.stdout: "access"
        co.elastic.logs/fileset.stderr: "error"
        co.elastic.metrics/module: nginx
        co.elastic.metrics/hosts: '${data.host}:80'
    spec:
      containers:
      - name: hello-tilt-front
        image: hello-tilt-front
        ports:
        - containerPort: 80
        env:
        - name: ENV_BACK1_URL
          valueFrom:
            secretKeyRef:
              name: front-secrets
              key: BACK1_URL
              optional: false
---
