apiVersion: v1
kind: Namespace
metadata:
  name: app1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-tilt-back
  namespace: app1
spec:
  selector:
    matchLabels:
      app: hello-tilt-back
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-tilt-back
    spec:
      containers:
      - name: hello-tilt-back
        image: hello-tilt-back
        ports:
        - containerPort: 80
