resources:
- kubernetes.yaml
secretGenerator:
- name: secrets
  namespace: app1
  behavior: merge
  envs:
  - .k8s_env_secret
configMapGenerator:
- name: config
  namespace: app1
  behavior: merge
  envs:
  - .k8s_env_config