global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  
  - job_name: "back1"
    metrics_path: /back1/metrics
    static_configs:
      - targets: ["host.docker.internal:8080"]
  
  - job_name: "back2"
    metrics_path: /back2/metrics
    static_configs:
      - targets: ["host.docker.internal:8080"]

  - job_name: otel
    static_configs:
      - targets:
        - 'otel-collector:9464'
  
  - job_name: otel-collector
    static_configs:
      - targets:
        - 'otel-collector:8888'