FROM alpine:latest as base

WORKDIR /app

RUN apk add --no-cache curl && \ 
    curl -L https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/3.10.2/rabbitmq_delayed_message_exchange-3.10.2.ez > rabbitmq_delayed_message_exchange-3.10.2.ez

FROM rabbitmq:3.10-management as final

COPY --from=base /app/rabbitmq_delayed_message_exchange-3.10.2.ez $RABBITMQ_HOME/plugins/rabbitmq_delayed_message_exchange-3.10.2.ez

RUN rabbitmq-plugins enable --offline rabbitmq_delayed_message_exchange rabbitmq_consistent_hash_exchange rabbitmq_shovel rabbitmq_shovel_management
RUN rabbitmq-plugins list
