apiVersion: v1
kind: Namespace
metadata:
  name: db
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-headless
  namespace: db
spec:
  ports:
  - port: 1433
  clusterIP: None
  selector:
    app: mssql
---
apiVersion: v1
kind: Service
metadata:
  name: mssql
  namespace: db
spec:
  type: NodePort
  ports:
  - port: 1433
    nodePort: 31437
  selector:
    statefulset.kubernetes.io/pod-name: mssql-0
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mssql
  namespace: db
spec:
  selector:
    matchLabels:
      app: mssql
  serviceName: "mssql-headless"
  replicas: 1
  template:
    metadata:
      labels:
        app: mssql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - containerPort: 1433
        env:
        - name: MSSQL_PID
          value: "Developer"
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          value: "Password1."
        volumeMounts:
        - name: mssql-data
          mountPath: /var/opt/mssql
        livenessProbe:
          exec:
            command: ["bash", "-c", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $MSSQL_SA_PASSWORD -d master -Q \"SELECT 1;\""]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command: ["bash", "-c", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $MSSQL_SA_PASSWORD -d master -Q \"SELECT 1;\""]
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 1
  volumeClaimTemplates:
  - metadata:
      name: mssql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "local-path"
      resources:
        requests:
          storage: 1Gi
